import{a as y,i as l,S as L}from"./assets/vendor-95dc692e.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();async function u(t,r){const s="https://pixabay.com/api/",a={key:"43018161-f974b102273f6260f6ed159b0",q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:15};try{return(await y.get(s,{params:a})).data}catch{iziToast.error({color:"red",message:"❌ Sorry, there was a mistake. Please try again!",position:"topRight"})}}function b(t){const{webformatURL:r,largeImageURL:s,tags:a,likes:e,views:o,comments:n,downloads:f}=t;return`<li class="gallery-item">
	<a class="gallery-link" href="${s}">
		<img
            src="${r}"
            alt="${a}"
            width="360"
            height="200"
            class="gallery-img"
        />
        <ul class="gallery-description">
        <li class="gallery-description-item"><h3>Likes</h3><p>${e}</p></li>
        <li class="gallery-description-item"><h3>Views</h3><p>${o}</p></li>
        <li class="gallery-description-item"><h3>Comments</h3><p>${n}</p></li>
        <li class="gallery-description-item"><h3>Downloads</h3><p>${f}</p></li>
     </ul>
	</a>
</li>`}function g(t){return t.map(b).join("")}const i={formEl:document.querySelector(".input-form"),infoEl:document.querySelector(".gallery"),btnLoadMore:document.querySelector(".load-btn"),card:document.querySelector(".gallery")};let m,d=1,h=0;const w=15,c=document.querySelector(".loader");i.formEl.addEventListener("submit",async t=>{if(t.preventDefault(),m=i.formEl.elements.query.value,d=1,m==="")l.warning({color:"yellow",message:"You forgot to describe the image",position:"topRight"}),i.infoEl.innerHTML="";else{i.infoEl.innerHTML="",c.classList.remove("is-hidden");try{const r=await u(m,d);h=Math.ceil(r.totalHits/w);const s=g(r.hits);i.infoEl.innerHTML=s,new L(".gallery-link",{captionsData:"alt",captionDelay:250,overlayOpacity:.8}).refresh(),s.length||(l.error({color:"red",message:"❌ Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),c.classList.add("is-hidden"))}catch{l.error({color:"red",message:"❌ Sorry, there was a mistake. Please try again!",position:"topRight"}),i.infoEl.innerHTML=""}finally{c.classList.add("is-hidden"),p()}}});i.btnLoadMore.addEventListener("click",S);async function S(){d+=1,c.classList.remove("is-hidden");try{const t=await u(m,d),r=g(t.hits);i.infoEl.insertAdjacentHTML("beforeend",r)}catch{l.error({color:"red",message:"❌ Sorry, there was a mistake. Please try again!",position:"topRight"}),i.infoEl.innerHTML=""}v(),p(),c.classList.add("is-hidden")}function p(){d>=h?(i.btnLoadMore.classList.add("is-hidden"),l.info({color:"blue",message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter"})):i.btnLoadMore.classList.remove("is-hidden")}function v(){const t=i.card.firstChild.getBoundingClientRect().height*2;scrollBy({top:t,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
